services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  server:
    build: ./server
    env_file: ./server/.env
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq

  workflow-engine:
    build: ./workflow-engine
    env_file: ./workflow-engine/.env
    depends_on:
      - rabbitmq

  document-processor:
    build: ./document-processor
    env_file: ./document-processor/.env
    ports:
      - '4000:4000'

  notification-service:
    build: ./notification-service
    env_file: ./notification-service/.env
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
