services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq

  workflow-engine:
    build:
      context: ./workflow-engine
      dockerfile: Dockerfile
    env_file:
      - ./workflow-engine/.env
    depends_on:
      - rabbitmq
